FinalProjectWebUI/Components/FooterViewComponent.cs
using FinalProjectWebUI.Models.DataContext;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FinalProjectWebUI.Components
{
    public class FooterViewComponent : ViewComponent
    {
        readonly FinalDbContext db;
        public FooterViewComponent(FinalDbContext db)
        {
            this.db = db;
        }


        public async Task<IViewComponentResult> InvokeAsync(int categorystore)
        {
            if (categorystore == 0)
            {
                categorystore = 1;
            }
            var store = db.SiteInfos.FirstOrDefault(p=> p.StoreId == categorystore);
            var social = db.SiteSocial.Include(p=>p.Social).Where(p => p.SiteInfoId == store.Id).ToList();
            return View(social);

        }
    }
}

FinalProjectWebUI/Components/HeaderViewComponent.cs
using FinalProjectWebUI.Models.DataContext;
using FinalProjectWebUI.Models.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FinalProjectWebUI.Components
{
    public class HeaderViewComponent : ViewComponent
    {
        readonly FinalDbContext db;
        public HeaderViewComponent(FinalDbContext db)
        {
            this.db = db;
        }


        public async Task<IViewComponentResult> InvokeAsync(string? order, int categorystore)
        {
            var vm = new FooterViewModel();
            if(categorystore== 0)
            {
                categorystore= 1;
            }
            vm.SiteInfo = db.SiteInfos.FirstOrDefault(p=> p.StoreId == categorystore);
            vm.SiteSocials = db.SiteSocial.Where(p => p.SiteInfoId == vm.SiteInfo.Id);
            vm.Categories = db.Categories.Include(p=> p.Products).Where(p=> p.Products.Count > 0).ToList();
            vm.Stores = db.Stores.Include(p=> p.SiteInfos).Where(p=> p.SiteInfos.Count() > 0).ToList();
            ViewBag.Order = order;


            return View(vm);

        }
    }
}

FinalProjectWebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
          crossorigin="anonymous" />
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css"
          integrity="sha512-tS3S5qG0BlhnQROyJXvNjeEM4UpMXHrQfTGmbQ1gKmelCxlSEBUaxhRBj/EFTzpbP4RVSrpEikbmdJobCvhE3g=="
          crossorigin="anonymous"
          referrerpolicy="no-referrer" />
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.min.css"
          integrity="sha512-sMXtMNL1zRzolHYKEujM2AqCLUR9F2C4/05cdbxjjLSRvMQIciEPCQZo++nk7go3BtSuK9kfa/s+a4f4i5pLkw=="
          crossorigin="anonymous"
          referrerpolicy="no-referrer" />
    <!-- font awesome -->
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css"
          integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ=="
          crossorigin="anonymous"
          referrerpolicy="no-referrer" />

    <link rel="stylesheet" href="~/assets/css/index.min.css" />
    <link rel="stylesheet" href="~/assets/css/filter.min.css" />
    <link rel="stylesheet" href="~/assets/css/openproduct.min.css" />
    <link rel="stylesheet" href="~/assets/css/guestcheckout.min.css" />
    <link rel="stylesheet" href="~/assets/css/login.min.css" />

    @RenderSection("addcss", false)
    <title>1</title>
</head>
<body>
    @await Component.InvokeAsync("Header", new{categorystore = ViewBag.Categorystore})
@RenderBody()
    @await Component.InvokeAsync("Footer", new{categorystore = ViewBag.Categorystore})
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.3/jquery.min.js"
            integrity="sha512-STof4xm1wgkfm7heWqFJVn58Hm3EtS31XFaagaa8VMReCXAkQnJZ+jEy8PCC/iT18dFy95WcExNHFTqLyp72eQ=="
            crossorigin="anonymous"
            referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"
            integrity="sha512-bPs7Ae6pVvhOSiIcyUClR7/q2OAsRiovw4vAkX+zJbw3ShAeeqezq50RIIcIURq7Oa20rW2n2q+fyXBNcU9lrw=="
            crossorigin="anonymous"
            referrerpolicy="no-referrer"></script>
    <script src="~/assets/js/index.js"></script>
    <script src="/assets/js/accordion.js"></script>
    <script>
                $('.basket-btn').click(function (z) {
            z.preventDefault();
            var id = $(this).data('id');

            $.ajax({
                type: 'Get',
                url: `/home/AddToCart/${id}`,
                success: function (response) {
                    if (response.error == false) {

                        var txt = $('#basket-cart').text();
                        var txt = parseInt(txt);
                        txt = txt + 1;
                        $('#basket-cart').text(txt);

                    }
                }

            });
        })

        $(document).on('change', '#price-max', function () {

            $('#price-max').val(`${$(this).val()}`);
            $('#amount').text(`Max price: ${$(this).val()}`);
        });
        $('.select-menu').mouseover(function () {
            $(".expand-menu").css("display", "block")
        })
        $('.expand-menu').mouseover(function () {
            $(".expand-menu").css("display", "block")
        })
        $('.expand-menu').mouseleave(function () {
            $(".expand-menu").css("display", "none")
        })
        $('.select-menu').mouseleave(function () {
            $(".expand-menu").css("display", "none")
        })


                $('.select-menu1').mouseover(function () {
            $(".expand-menu1").css("display", "block")
        })
        $('.expand-menu1').mouseover(function () {
            $(".expand-menu1").css("display", "block")
        })
        $('.expand-menu1').mouseleave(function () {
            $(".expand-menu1").css("display", "none")
        })
        $('.select-menu1').mouseleave(function () {
            $(".expand-menu1").css("display", "none")
        })
    </script>
    @RenderSection("addjs", false)
</body>
</html>